### ISSUE TITLE
Input format validation

### ISSUE THREAD

**Issue by jbochi** [globocom/hlsclient#31]
We don't provide descriptive error messages if the input `json` is not valid.

If there are duplicated playlists keys, it will fail silently (See issue #28).

**Comment by jbochi** [comment]
Sample traceback for malformed input json, with a combine action for invalid playlist:

```
Traceback (most recent call last):
  File "/opt/generic/python27/lib/python2.7/site-packages/hlsclient/__main__.py", line 51, in main
    combine_playlists(playlists, destination)
  File "/opt/generic/python27/lib/python2.7/site-packages/hlsclient/combine.py", line 10, in combine_playlists
    dump_variant_playlist(playlists_data, action, path)
  File "/opt/generic/python27/lib/python2.7/site-packages/hlsclient/combine.py", line 29, in dump_variant_playlist
    m3u8 = generate_variant_playlist(playlists_data, action)
  File "/opt/generic/python27/lib/python2.7/site-packages/hlsclient/combine.py", line 36, in generate_variant_playlist
    playlist = generate_single_playlist(playlists_data[playlist_name])
KeyError: u'pgma_audio'
```
